# Indexing and slicing array 


In [1]:
import numpy as np

In [24]:
arr = np.arange(5,50,5)

In [25]:
arr

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [26]:
arr[:3]

array([ 5, 10, 15])

In [27]:
arr = arr.reshape(3,-1)

In [29]:
arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

# indexing in 2d array Using double quotation 

In [34]:
print(arr)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [35]:
arr[1][2]   

30

In [36]:
arr[0][2]



15

# indexing  & slicing using single quation 

In [38]:
print(arr) # print the array

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [39]:
arr[0,0] # using single quation find 1st elemet

5

In [40]:
# [[5,10] 
# [20 25]] 

In [42]:
print(arr[:2,:2])

[[ 5 10]
 [20 25]]


In [43]:
# [[25,30]
#   [40,45 ]]

In [44]:
print(arr[1:, 1:])

[[25 30]
 [40 45]]


In [46]:
np.random.seed(123)
matrix  = np.random.randint(1,101,25).reshape(5,-1)
matrix


array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [ ]:
'''[[97 , 98, 97]
 [33, 47, 97 ]  # creat krna h aise matrix 
 [79 , 37 , 97]]'''

In [49]:
matrix[1:4,1:-1] # first argument for row and second argument for column 

array([[87, 98, 97],
       [33, 47, 97],
       [79, 37, 97]])